version: '3.9'

services:
  db:
    image: postgres:16
    container_name: semesterproject-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: semesterproject
    ports:
      - "5435:5432"   # außen 5433 → innen 5432)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: